2019-10-03 15:11:08,062 INFO: Microblog startup [in /mnt/nfs/home/zula/projects/flask-tutorial/app/__init__.py:74]
2019-10-03 15:11:10,278 ERROR: Exception on / [GET] [in /mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/app/main/routes.py", line 46, in index
    prev_url=prev_url)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/mnt/nfs/home/zula/projects/flask-tutorial/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/mnt/nfs/home/zula/projects/flask-tutorial/app/templates/base.html", line 17, in block "navbar"
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2019-10-03 15:12:28,722 INFO: Microblog startup [in /mnt/nfs/home/zula/projects/flask-tutorial/app/__init__.py:74]
2019-10-03 15:12:32,447 ERROR: Exception on / [GET] [in /mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/app/main/routes.py", line 46, in index
    prev_url=prev_url)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/mnt/nfs/home/zula/projects/flask-tutorial/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/mnt/nfs/home/zula/projects/flask-tutorial/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/mnt/nfs/home/zula/projects/flask-tutorial/app/templates/index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "/mnt/nfs/home/zula/projects/flask-tutorial/app/templates/_post.html", line 4, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/mnt/nfs/home/zula/projects/flask-tutorial/venv/lib64/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
2019-10-03 15:18:03,467 INFO: Microblog startup [in /mnt/nfs/home/zula/projects/flask-tutorial/app/__init__.py:74]
